spring:
  datasource:
    url: jdbc:mysql://localhost:3306/BTS?useUnicode=true&characterEncoding=utf8&serverTimezone=UTC
    username: root
    password: 
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        #        show_sql: true
        format_sql: true

logging.level:
  org.hibernate.SQL: debug
#  org.hibernate.type: trace

jwt:
  secret: secret
  access_expiration: 3600
  refresh_expiration: 86400
