spring:
  datasource:
    url: jdbc:mysql://localhost:3305/BTS
    username: root
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        show_sql: true
        format_sql: true

  mail:
    host: smtp.gmail.com
    port: 587
    username: "busantripteam@gmail.com"
    password: "ltgq bmqo xoat xbiz"
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
          ssl:
            trust: smtp.gmail.com
            enable: true
        debug: true

  data:
    redis:
      repositories:
        enabled: false

logging.level:
  org.hibernate.SQL: debug
#  org.hibernate.type: trace

jwt:
  secret: secret
  access_expiration: 3600
  refresh_expiration: 86400

# 레디스 두개 사용
# 1. Refresh 토큰용
redis1:
    host: localhost
    port: 6379

# 2. Mail 인증용
redis2:
    host: localhost
    port: 6380


server:
  port: 8080
